name: iOS Build

on:
  push:
    branches:
      - main  # Run when pushing to main branch 
  pull_request:
    branches:
      - main  # Run on pull requests

jobs:
  build-ios:
    runs-on: macos-latest  # Use macOS runner (FREE in GitHub Actions)

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.x"  # Change to your Flutter version
          cache: true  # Enable caching for faster builds

      - name: Install Dependencies
        run: |
          pwd  # Print the current working directory for debugging
          ls -l  # List files to check if pubspec.yaml exists
          flutter pub get

      - name: Install CocoaPods Dependencies
        run: |
          cd ios
          pod install

      - name: Build iOS (Without Code Signing)
        run: flutter build ios --no-codesign

      - name: Archive Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: iOS-App
          path: build/ios/iphoneos/*.app
